version: 2.1
orbs:
  node: circleci/node@4.1

jobs:
  run-test:  
    docker:
      - image: cimg/node:15.1
    resource_class: small
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test:ci

workflows:
  Pull request: 
    jobs:
      - run-test:
          context:
            - test 
            - build-and-test
